
###
### Kafka Vars
###
  kafka_download_url: https://mirrors.ukfast.co.uk/sites/ftp.apache.org/kafka/2.7.0/kafka_2.13-2.7.0.tgz
  kafka_download_dir: /opt/
  kafka_download_file: kafka_2.13-2.7.0
  kafka_download_file_perms: 0744

  kafka_home: /opt/kafka
  kafka_user: kafka
  kafka_group: kafka
  kafka_user_shell: /bin/bash

  kafka_log_dir: /tmp/kafka
  kafka_broker_id: 0

  kafka_properties_template: server.properties.j2
  kafka_sysd_service_template: kafka.service.j2

  sysd_service_owner: root
  sysd_service_group: root
  sysd_file_perm: 0644

  kafka_service_name: kafka.service
  kafka_service_name_perm: 0644
  kafka_properties_file: config/server.properties
  kafka_properties_file_perm: 0644

  kafka_start_script: bin/kafka-server-start.sh
  kafka_stop_script: bin/kafka-server-stop.sh

###
### Zookeeper Vars
###
  zk_properties_template: zookeeper.properties.j2
  zk_sysd_service_template: zookeeper.service.j2

  zk_service_name: zookeeper.service
  zk_service_name_perm: 0644
  zk_properties_file: config/zookeeper.properties
  zk_properties_file_perm: 0644

  zk_start_script: bin/zookeeper-server-start.sh
  zk_stop_script: bin/zookeeper-server-stop.sh

  zk_nodes: localhost:2181
  zk_data_dir: /tmp/zookeeper
  zk_port: 2181



###
### Scripts
###

  scripts_dir: /home/kafka
  script_perms: 0744

  create_template: createTopic.sh.j2
  describe_template: describeTopic.sh.j2
  list_template: listTopics.sh.j2
  test_template: kafkaTopicTest.sh.j2

  create_script: createTopic.sh
  describe_script: describeTopic.sh
  list_script: listTopics.sh
  test_script: kafkaTopicTest.sh
