
- name: Load OS specific Vars
  include_vars: redhat.yml

- name: Install Unzip
  ansible.builtin.yum:
   name: "{{ unzip_package }}"
   state: present

- name: Install Java
  ansible.builtin.yum:
   name: "{{ java_package }}"
   state: present
